theme: jekyll-theme-cayman
title: Secret LED message challenge
description: Use computer vision to reveal a message that humans find hard to decipher...then use what you have made to find our who has won a race!
